language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"
install:
 - "pip install -e .[test]"
script:
 - "flake8 ."
   # the dot for pytest is for 3.3 compatibility:
 - "py.test --cov=svgast --cov-report=term-missing --cov-branch"
